spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/flowable-spring-boot-2?characterEncoding=UTF-8&nullCatalogMeansCurrent=true
    username: root
    password: allcom

flowable:
#关闭定时任务JOB
  async-executor-activate: false